"""empty message

Revision ID: 578849785fd4
Revises: 5c1680b9dad8
Create Date: 2017-10-24 18:55:50.138430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578849785fd4'
down_revision = '5c1680b9dad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'create_time')
    # ### end Alembic commands ###
